version: "3.9"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8001:8000"
    env_file:
      - .env

  streamlit:
    image: python:3.11-slim
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app:/app
      - ./backend:/backend
    working_dir: /app
    command: bash -c "pip install streamlit && streamlit run app.py"
    depends_on:
      - backend
