version: "3.9"

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=America/New_York
    volumes:
      - n8n_data:/home/node/.n8n

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8001:8000"
    depends_on:
      - ollama

  streamlit:
    image: python:3.11-slim
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app:/app
    working_dir: /app
    command: bash -c "pip install streamlit && streamlit run app.py"
    depends_on:
      - backend

volumes:
  n8n_data:
  ollama_data:
