version: "3.9"

services:
  backend:
    build: ./backend
    platform: linux/amd64  # Force x86_64 architecture for Playwright compatibility
    volumes:
      - ./backend:/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8001:8000"
    env_file:
      - .env

  frontend:
    build: ./frontend
    platform: linux/amd64  # Keep frontend consistent too
    ports:
      - "3000:80"
    depends_on:
      - backend
